version: "3.8"

services:
  bot:
    build:
      context: ./src
    container_name: bot
    working_dir: /src
    command: sh -c "python core.py"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://bot:bot-QWErty!2@db:5432/bot
    volumes:
      - ./src:/src
  db:
    image: postgres:16-alpine
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=bot-QWErty!2
      - POSTGRES_DB=bot
      - POSTGRES_HOST_AUTH_METHOD=trust
  django:
    build: ./admin
    command: sh -c "python manage.py collectstatic; python manage.py migrate; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./admin:/admin
      - static_data:/admin/static
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://bot:bot-QWErty!2@db:5432/bot
      - DEBUG=1
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static/
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  static_data: